### ISSUE TITLE
NullpointerException at MinifyBibtexAuthors

### ISSUE THREAD

**Issue by stefan-kolb** [simonharrer/textools#9]
Probably due to missing author field in, e.g. Standards.

```java  
null
java.lang.NullPointerException
        at textools.commands.MinifyBibtexAuthors.minifyDatabase(MinifyBibtexAuthors.java:45)
        at textools.commands.MinifyBibtexAuthors.execute(MinifyBibtexAuthors.java:32)
        at textools.Main.main(Main.java:37)
```

**Comment by stefan-kolb** [comment]
#11
